language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href /
after_success:
  - find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://jelleglebbeek.com/jelleglebbeek/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;
